version: "3"
services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    depends_on:
      - nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
  db:
    image: mysql:8.0
    container_name: "efficientree-DB"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    tty: true

  api:
    build: ./api
    container_name: "efficientree-API"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec pumactl start"
    volumes:
      - ./api:/myapp
      - ./certs:/certs
    ports:
      - "3000:9292"
    environment:
      RAILS_ENV: production
      VIRTUAL_HOST: efficientree-api.nutfes.net
      LETSENCRYPT_HOST: efficientree-api.nutfes.net
    depends_on:
      - db
    stdin_open: true
    tty: true

  view:
    build: ./view
    container_name: "efficientree-VIEW"
    ports:
      - "8080:8080"
    command: npm run serve
    volumes:
      - ./view:/app
    stdin_open: true
    tty: true
    environment:
      VUE_APP_URL: https://efficientree-api.nutfes.net #http://localhost:3000
      VIRTUAL_HOST: efficientree.nutfes.net
      LETSENCRYPT_HOST: efficientree.nutfes.net
    depends_on:
      - api

volumes:
  mysql-data:
    driver: local
  html:
  vhost:
  dhparam: