FROM node:12.14.1

ENV NODE_ENV=production
ENV VUE_APP_URL='https://efficientree-api.nutfes.net'
ENV NODE_OPTIONS=--max_old_space_size=512

ENV APP_HOME /app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

RUN npm install -g @vue/cli
COPY ./package*.json /app/
COPY ./ /app/
RUN npm install


RUN npm install --save axios

RUN npm run build
